# 智慧校园管理系统 - 统一配置文件
server:
  port: 8889  # 开发环境端口（避免端口冲突）
  # HTTP传输配置，解决chunked编码问题
  http2:
    enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    min-response-size: 1024
  tomcat:
    connection-timeout: 30000
    max-connections: 8192
    max-http-form-post-size: 2MB
    max-swallow-size: 2MB
    threads:
      max: 200
      min-spare: 10
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false

spring:
  application:
    name: campus_management_db
  


  profiles:
    active: dev  # 默认激活开发环境

  # 启动横幅配置
  main:
    banner-mode: console
    allow-circular-references: true

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_management_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=3&useAffectedRows=true&createDatabaseIfNotExist=true
    username: root
    password: xiaoxiao123
    # HikariCP连接池配置
    hikari:
      pool-name: HikariCP
      minimum-idle: 2
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      validation-timeout: 3000
      connection-test-query: SELECT 1

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none  # 临时禁用DDL自动更新
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        '[format_sql]': false
        '[use_sql_comments]': false
        '[query.timeout]': 5000
        '[connection.provider_disables_autocommit]': false
        '[enable_lazy_load_no_trans]': false
        '[current_session_context_class]': thread
        '[connection.release_mode]': after_transaction
        '[generate_statistics]': false
        '[query.plan_cache_max_size]': 2048
        jdbc:
          '[batch_size]': 20
        '[order_inserts]': true
        '[order_updates]': true
    open-in-view: true

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

  # 缓存配置 - 使用Redis缓存
  cache:
    type: redis
    redis:
      time-to-live: 1800000  # 30分钟

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: test@qq.com
    password: test-password
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 开发环境禁用缓存

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true

  # 国际化配置
  messages:
    basename: messages
    encoding: UTF-8

# 自定义配置
campus:
  # JWT配置
  jwt:
    secret: campus-management-jwt-secret-key-dev-2024
    expiration: 7200000        # 2小时
    refresh-expiration: 604800000  # 7天
    header: Authorization
    prefix: Bearer
    redis:
      enabled: true
      prefix: "jwt:token:"
      refresh-prefix: "jwt:refresh:"

  # 应用配置
  app:
    name: 智慧校园管理系统
    version: 1.0.0
    description: 智慧校园综合管理平台
    jwt:
      secret: campus-management-jwt-secret-key-dev-2024
      expiration: 7200000
      refresh-expiration: 604800000

  # 系统配置
  system:
    name: 智慧校园管理系统
    version: 1.0.0
    # author: Campus Management Team  # Removed due to unknown property error
    # domain: localhost:8889  # Removed due to unknown property error
    debug: false

  # 文件上传配置
  upload:
    enabled: true
    path: uploads/
    # max-file-size: 10MB  # 10MB  # Commented out to avoid unknown property error
    allowed-types: 
      - jpg
      - jpeg
      - png
      - gif
      - pdf
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - txt
      - zip
      - rar

  # 安全配置
  security:
    enabled: true
    password:
      min-length: 6
      max-attempts: 5
      strength-check: true
      lockout-duration: 300000  # 5分钟
    session:
      timeout: 1800
      max-sessions: 1
    captcha:
      enabled: true
      length: 4
      expire: 300
    ignored-urls:
      - /api/v1/auth/login
      - /api/v1/auth/register
      - /api/v1/auth/captcha
      - /swagger-ui/**
      - /api/v1/api-docs/**

  # 业务配置
  business:
    enable-notification: true
    enable-audit: true
    default-page-size: 20
    # 选课配置
    course-selection:
      enabled: true
      max-courses-per-student: 10
      allow-drop-after-deadline: false
    # 成绩配置
    grade:
      enabled: true
      scale: 100
      pass-score: 60
      gpa-scale: 4.0
    # 缴费配置
    payment:
      enabled: true
      reminder-days: 7
      late-fee-rate: 0.001

  # 缓存配置
  cache:
    enabled: true
    type: redis
    default-ttl: 1800  # 30分钟
    # 具体缓存TTL配置
    course-ttl: 1800      # 课程信息缓存 - 30分钟
    permission-ttl: 900   # 用户权限缓存 - 15分钟
    config-ttl: 3600      # 系统配置缓存 - 1小时
    student-ttl: 1800     # 学生信息缓存 - 30分钟
    class-ttl: 3600       # 班级信息缓存 - 1小时

  # 性能监控配置
  monitor:
    enabled: false  # 临时禁用监控
    endpoints:
      - health
      - metrics
      - info
    redis-monitor-interval: 60000  # Redis监控间隔 1分钟
    performance-log: false  # 临时禁用性能日志

  # 邮件配置
  mail:
    enabled: false  # 暂时禁用邮件
    template-path: classpath:/templates/email/
    from-name: 智慧校园管理系统
    admin-emails:
      - admin@campus.edu.cn

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,redis
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: smart-campus-management
      environment: dev
  prometheus:
    metrics:
      export:
        enabled: true

# 日志配置 - 开发环境（增加详细输出用于调试）
logging:
  level:
    '[com.campus]': DEBUG
    '[com.campus.interfaces.rest.v1.auth]': DEBUG
    '[com.campus.application.Implement.auth]': DEBUG
    '[com.campus.shared.util.JwtTokenUtil]': DEBUG
    '[com.campus.shared.security]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.springframework.web.servlet.DispatcherServlet]': DEBUG
    '[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]': DEBUG
    '[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]': DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  info:
    title: 智慧校园管理系统API
    description: 智慧校园管理系统的RESTful API文档
    version: 1.0.0
    contact:
      name: Campus Management Team
      email: support@campus.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
