# 智慧校园管理系统 - 主配置文件
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 响应压缩配置
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  
  # HTTP配置
  tomcat:
    connection-timeout: 20000  # 20秒连接超时
    keep-alive-timeout: 60000  # 60秒保活超时
    max-keep-alive-requests: 100
    accept-count: 100
    max-connections: 200
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: smart-campus-management

  profiles:
    active: dev  # 默认激活开发环境

  # 启动横幅配置
  main:
    banner-mode: console

  # Thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # 国际化配置
  messages:
    basename: messages
    encoding: UTF-8

# 自定义配置
campus:
  # 系统配置
  system:
    name: 智慧校园管理系统
    version: 1.0.0
    author: Campus Team

  # 文件上传配置
  upload:
    path: uploads/
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx

  # 安全配置
  security:
    password:
      min-length: 6
      max-attempts: 5
    session:
      timeout: 1800
