# 开发环境配置
server:
  port: 8082

spring:
  # 数据源配置 - 开发环境
  datasource:
    url: jdbc:mysql://localhost:3306/campus_management_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=3&useAffectedRows=true
    username: root
    password: xiaoxiao123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # HikariCP 连接池配置（Spring Boot 默认）
    hikari:
      # 连接池中允许的最小连接数
      minimum-idle: 2
      # 连接池中允许的最大连接数
      maximum-pool-size: 50
      # 自动提交
      auto-commit: true
      # 连接超时时间，毫秒
      connection-timeout: 30000
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      # 连接池最大生存时间，0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间，默认30秒，即30000
      validation-timeout: 3000
      # 心跳检测查询语句
      connection-test-query: SELECT 1

  # Redis 配置 - 开发环境
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 1800000  # 30分钟默认过期时间

  # 邮件配置 - 开发环境（使用测试邮箱）
  mail:
    host: smtp.qq.com
    port: 587
    username: test@qq.com
    password: test-password
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # JPA配置 - 开发环境
  jpa:
    hibernate:
      ddl-auto: update  # 改回update，允许自动更新表结构
      naming:
        # 使用Spring Boot 3.x兼容的命名策略
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false  # 关闭SQL日志减少输出
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        # 查询超时配置
        query.timeout: 5000
        # 连接配置
        connection.provider_disables_autocommit: false  # 启用自动提交
        # 懒加载配置
        enable_lazy_load_no_trans: false
        # 事务配置
        current_session_context_class: thread
        # 连接释放模式
        connection.release_mode: after_transaction
    open-in-view: true  # 启用open-in-view解决懒加载问题

  # Quartz 配置 - 开发环境
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
            threadPriority: 5
          scheduler:
            instanceName: CampusScheduler-Dev
            instanceId: AUTO

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: true
    # 延迟加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    # 查询超时时间
    default-statement-timeout: 30
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # ID 生成策略
      id-type: ASSIGN_ID

# JWT配置 - 开发环境
jwt:
  secret: campus-management-jwt-secret-key-dev-2024
  expiration: 7200000        # 2小时
  refresh-expiration: 604800000  # 7天
  header: Authorization
  prefix: Bearer
  redis:
    prefix: "jwt:token:"
    refresh-prefix: "jwt:refresh:"

# 日志配置 - 开发环境（减少输出）
logging:
  level:
    com.campus: INFO
    org.springframework: WARN
    org.springframework.security: WARN
    org.springframework.data: WARN
    org.springframework.cache: WARN
    org.springframework.boot: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    org.apache.tomcat: WARN
    org.apache.catalina: WARN
    org.mybatis: WARN
    org.quartz: WARN
    io.lettuce: WARN
    root: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{20} - %msg%n"

# 管理端点配置 - 开发环境
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,redis
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: smart-campus-management
      environment: dev



# 自定义配置
campus:
  # 缓存配置
  cache:
    # 课程信息缓存 - 30分钟
    course-ttl: 1800
    # 用户权限缓存 - 15分钟
    permission-ttl: 900
    # 系统配置缓存 - 1小时
    config-ttl: 3600
    # 学生信息缓存 - 30分钟
    student-ttl: 1800
    # 班级信息缓存 - 1小时
    class-ttl: 3600

  # 性能监控配置
  monitor:
    enabled: false  # 临时禁用监控
    redis-monitor-interval: 60000  # Redis监控间隔 1分钟
    performance-log: false  # 临时禁用性能日志

  # 邮件模板配置
  mail:
    template-path: classpath:/templates/email/
    from-name: 智慧校园管理系统
