# 智慧校园管理系统 - 统一配置文件
server:
  port: 8082  # 开发环境端口

spring:
  application:
    name: smart-campus-management

  profiles:
    active: dev  # 默认激活开发环境

  # 启动横幅配置
  main:
    banner-mode: console

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_management_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=3&useAffectedRows=true
    username: root
    password: xiaoxiao123
    # HikariCP连接池配置
    hikari:
      pool-name: HikariCP
      minimum-idle: 2
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      validation-timeout: 3000
      connection-test-query: SELECT 1

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        use_sql_comments: false
        query.timeout: 5000
        connection.provider_disables_autocommit: false
        enable_lazy_load_no_trans: false
        current_session_context_class: thread
        connection.release_mode: after_transaction
        generate_statistics: false
        query.plan_cache_max_size: 2048
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: true

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 1800000  # 30分钟

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: test@qq.com
    password: test-password
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Quartz配置
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
            threadPriority: 5
          scheduler:
            instanceName: CampusScheduler-Dev
            instanceId: AUTO

  # Thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 开发环境禁用缓存

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true

  # 国际化配置
  messages:
    basename: messages
    encoding: UTF-8

# JWT配置
jwt:
  secret: campus-management-jwt-secret-key-dev-2024
  expiration: 7200000        # 2小时
  refresh-expiration: 604800000  # 7天
  header: Authorization
  prefix: Bearer
  redis:
    prefix: "jwt:token:"
    refresh-prefix: "jwt:refresh:"

# 自定义配置
campus:
  # 系统配置
  system:
    name: 智慧校园管理系统
    version: 1.0.0
    author: Campus Team
    domain: localhost:8082

  # 文件上传配置
  upload:
    path: uploads/
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar

  # 安全配置
  security:
    password:
      min-length: 6
      max-attempts: 5
      strength-check: true
    session:
      timeout: 1800
    captcha:
      enabled: true
      length: 4
      expire: 300

  # 业务配置
  business:
    # 选课配置
    course-selection:
      max-courses-per-student: 10
      allow-drop-after-deadline: false
    # 成绩配置
    grade:
      scale: 100
      pass-score: 60
      gpa-scale: 4.0
    # 缴费配置
    payment:
      reminder-days: 7
      late-fee-rate: 0.001

  # 缓存配置
  cache:
    # 课程信息缓存 - 30分钟
    course-ttl: 1800
    # 用户权限缓存 - 15分钟
    permission-ttl: 900
    # 系统配置缓存 - 1小时
    config-ttl: 3600
    # 学生信息缓存 - 30分钟
    student-ttl: 1800
    # 班级信息缓存 - 1小时
    class-ttl: 3600

  # 性能监控配置
  monitor:
    enabled: false  # 临时禁用监控
    redis-monitor-interval: 60000  # Redis监控间隔 1分钟
    performance-log: false  # 临时禁用性能日志

  # 邮件模板配置
  mail:
    template-path: classpath:/templates/email/
    from-name: 智慧校园管理系统

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,redis
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: smart-campus-management
      environment: dev

# 日志配置 - 开发环境（减少输出）
logging:
  level:
    com.campus: INFO
    org.springframework: WARN
    org.springframework.security: ERROR
    org.springframework.data: ERROR
    org.springframework.cache: ERROR
    org.springframework.boot: ERROR
    org.springframework.web: ERROR
    org.springframework.orm: ERROR
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    org.hibernate.stat: ERROR
    org.hibernate.engine: ERROR
    org.apache.tomcat: ERROR
    org.apache.catalina: ERROR
    com.zaxxer.hikari: ERROR
    com.zaxxer.hikari.HikariConfig: ERROR
    com.zaxxer.hikari.pool: ERROR
    org.quartz: ERROR
    io.lettuce: ERROR
    io.netty: ERROR
    org.apache.http: ERROR
    org.apache.commons: ERROR
    org.springframework.transaction: ERROR
    root: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{15} - %msg%n"

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  info:
    title: 智慧校园管理系统API
    description: 智慧校园管理系统的RESTful API文档
    version: 1.0.0
    contact:
      name: Campus Management Team
      email: support@campus.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
