# 生产环境配置文件 - 优化日志输出
server:
  port: 8080

spring:
  # JPA配置 - 生产环境优化
  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境使用validate，不自动更新数据库结构
    show-sql: false       # 完全禁用SQL日志
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        use_sql_comments: false
        # 生产环境性能优化
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: true
          use_query_cache: true

# 生产环境日志配置 - 最小化日志输出
logging:
  level:
    # 应用程序只记录WARN及以上级别
    com.campus: WARN
    # Spring框架只记录ERROR级别
    org.springframework: ERROR
    # Spring Security只记录ERROR级别
    org.springframework.security: ERROR
    # Hibernate只记录ERROR级别
    org.hibernate: ERROR
    # 数据库连接池只记录ERROR级别
    com.zaxxer.hikari: ERROR
    # Tomcat只记录ERROR级别
    org.apache.catalina: ERROR
    # 根日志级别设置为WARN
    root: WARN
  pattern:
    # 简化控制台日志格式
    console: "%d{HH:mm:ss} %-5level %logger{20} - %msg%n"
    # 详细的文件日志格式
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/campus-management.log
    max-size: 50MB      # 增大单个日志文件大小
    max-history: 7      # 减少保留的日志文件数量

# 管理端点配置 - 生产环境安全配置
management:
  endpoints:
    web:
      exposure:
        include: health,info  # 只暴露必要的端点
  endpoint:
    health:
      show-details: never     # 不显示详细健康信息
