# 智慧校园管理系统 - 主配置文件
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: smart-campus-management

  profiles:
    active: dev  # 默认激活开发环境

  # Thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # 国际化配置
  messages:
    basename: messages
    encoding: UTF-8

# 自定义配置
campus:
  # 系统配置
  system:
    name: 智慧校园管理系统
    version: 1.0.0
    author: Campus Team

  # 文件上传配置
  upload:
    path: uploads/
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx

  # 安全配置
  security:
    password:
      min-length: 6
      max-attempts: 5
    session:
      timeout: 1800
